# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: maudsley 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "maudsley"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["YuuShigetani"]
  s.date = "2014-06-15"
  s.description = "Maudsley can deploy all of its guts into a folder. This allows it to be used without having to worry about external dependencies."
  s.email = "s2g4t1n2@gmail.com"
  s.executables = ["maudsley"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "assets/Rakefile",
    "assets/project.yml",
    "bin/maudsley",
    "example/spec/cpi_spec.c",
    "example/spec/fabs_spec.c",
    "example/spec/strcmp_spec.c",
    "example/src/cpi.c",
    "example/src/cpi.h",
    "lib/maudsley.rb",
    "lib/maudsley/accessor.rb",
    "lib/maudsley/cli.rb",
    "lib/maudsley/configurator.rb",
    "lib/maudsley/generator.rb",
    "lib/maudsley/rakefile.rb",
    "lib/maudsley/runner.rb",
    "maudsley.gemspec",
    "spec/maudsley_spec.rb",
    "spec/spec_helper.rb",
    "tasks/tests.rake",
    "template/Gemfile.erb",
    "template/main_spec.c.erb"
  ]
  s.homepage = "http://github.com/calorie/maudsley"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Maudsley is a set of tools for the automation of builds and test running for MPI."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

